export const OPEN_MODAL_TO_LOGIN = 'OPEN_MODAL_TO_LOGIN ';
export const OPEN_MODAL_TO_REGISTRATION = 'OPEN_MODAL_TO_REGISTRATION';
export const SWITCH_TO_MODAL_TO_LOGIN = 'SWITCH_TO_LOGIN';
export const SWITCH_TO_MODAL_TO_SUCCESS = 'SWITCH_TO_MODAL_TO_SUCCESS';

export const USER_REGISTRATION_START = 'REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const REQUEST_CREATION_START = 'REQUEST_CREATION_START';
export const REQUEST_CREATION_SUCCESS = 'REQUEST_CREATION_SUCCESS';
export const REQUEST_CREATION_FAIL = 'REQUEST_CREATION_FAIL';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const REQUEST_FETCHING_START = 'REQUEST_FETCHING_START';
export const REQUEST_FETCHING_SUCCESS = 'REQUEST_FETCHING_SUCCESS';
export const REQUEST_FETCHING_FAIL = 'REQUEST_FETCHING_FAIL';
