export const OPEN_MODAL_TO_LOGIN = 'OPEN_MODAL_TO_LOGIN ';
export const OPEN_MODAL_TO_REGISTRATION = 'OPEN_MODAL_TO_REGISTRATION';
export const SWITCH_TO_MODAL_TO_LOGIN = 'SWITCH_TO_LOGIN';
export const SWITCH_TO_MODAL_TO_SUCCESS = 'SWITCH_TO_MODAL_TO_SUCCESS';

export const USER_REGISTRATION_START = 'REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'REGISTRATION_FAIL';